title: Aergia
description: The most minimal yet still usable programming language.
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

url: https://las-r.github.io/aergia
baseurl: /aergia

aux_links:
  "GitHub":
    - https://github.com/las-r/aergia
