source "https://rubygems.org"
gem "jekyll", "~> 4.3"

group :jekyll_plugins do
  gem "just-the-docs", "~> 0.7"
  gem "jekyll-remote-theme"
  gem "jekyll-default-layout"
  gem "jekyll-optional-front-matter"
  gem "jekyll-readme-index"
  gem "jekyll-titles-from-headings"
  gem "kramdown-parser-gfm"
end